(DEFINE-CONFIGURATION WEB-BUFFER
  ((DEFAULT-MODES '(EMACS-MODE CERTIFICATE-EXCEPTION-MODE WEB-MODE BASE-MODE))))
(DEFINE-CONFIGURATION BUFFER
  ((CURRENT-ZOOM-RATIO 2)))
(DEFINE-CONFIGURATION WEB-BUFFER
  ((DEFAULT-MODES '(EMACS-MODE CERTIFICATE-EXCEPTION-MODE WEB-MODE BASE-MODE))))
(DEFINE-CONFIGURATION (BUFFER WEB-BUFFER)
  ((DEFAULT-MODES (APPEND '(EMACS-MODE) %SLOT-DEFAULT))))
